apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-test-nginx
  template:
    metadata:
      labels:
        app: argo-test-nginx
    spec:
      containers:
        - name: nginx-for-argo
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: nginx-http-port
