apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-test-nginx
  template:
    metadata:
      labels:
        app: argo-test-nginx
    spec:
      containers:
        - name: nginx-for-argo
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: nginx-http-port
          volumeMounts:
            - name: index-html-volume
              mountPath: /usr/share/nginx/html/

      initContainers:
        - name: get-pod-hostname
          image: busybox
          command: ['sh', '-c', "hostname > /index-volume-mount/index.html"]
          volumeMounts:
            - name: index-html-volume
              mountPath: /index-volume-mount
      volumes:
        - name: index-html-volume
          emptyDir: {}

